#!/usr/bin/env bash

SCRIPT_DIRECTORY=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

VERBOSE="false"
VERBOSE_ALL="false"
while getopts "vV" OPTION; do
  case "$OPTION" in
    v) VERBOSE="true";;
    V) VERBOSE_ALL="true";;
  esac
done
shift "$((OPTIND-1))"

if [[ "$VERBOSE" == "true" || "$VERBOSE_ALL" == "true" ]]; then
  printf 'Building: "ubuntu-base"\n\n'

  docker build --file "$SCRIPT_DIRECTORY/Dockerfile" --pull --tag ubuntu-base "$SCRIPT_DIRECTORY"
else
  docker build --quiet --file "$SCRIPT_DIRECTORY/Dockerfile" --pull --tag ubuntu-base "$SCRIPT_DIRECTORY"
fi
